version: "3"

services:
  users:
    build: ./microservices/user-service

  cars:
    build: ./microservices/car-service

  books:
    build: ./microservices/book-service

  nginx:
    image: nginx:latest
    ports:
      - "8000:7000"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - users
      - books
      - cars
