version: "3"

# Services
services:
  users:
    container_name: user-service
    build: ./microservices/user-service
    networks:
      - app-network

  cars:
    container_name: car-service
    build: ./microservices/car-service
    networks:
      - app-network

  books:
    container_name: book-service
    build: ./microservices/book-service
    networks:
      - app-network

  # BACKEND
  backend:
    build: ./microservices/backend-service
    container_name: backend-service
    tty: true
    ports:
      - "8080:8080"
    networks:
      - app-network

  # WEBSERVER
  webserver:
    image: nginx:1.19.9
    container_name: nginx-1.19.9
    tty: true
    restart: unless-stopped
    ports:
      - "71:70"
      - "81:80"
      - "91:90"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      #- ./nginx/nginx.php.conf:/etc/nginx/conf.d/site.conf
    networks:
      - app-network
    depends_on:
      - users
      - books
      - cars
      - backend

# Docker Networks
networks:
  app-network:
    name: app-network
    driver: bridge
    external: true
