services:
  db:
    image: container-registry.oracle.com/database/free:latest
    #restart: always
    container_name: oracle-free
    environment:
      ORACLE_PWD: zayro
    ports:
      - 1521:1521
    volumes:
      - app-data-oracle:/opt/oracle/oradata
      - ./tnsnames.ora:/opt/oracle/product/23ai/dbhomeFree/network/admin/tnsnames.ora
    networks:
      app-network:
        aliases:
          - oracle-db

# Volumes
volumes:
  app-data-oracle:
    #name: app-data
    #driver: local
    external: true

# Docker Networks
networks:
  app-network:
    name: app-network
    driver: bridge
    external: true
