version: "3"

# Services
services:
  # DATABASE
  server:
    build: ./
    container_name: nginx
    tty: true
    #restart: always
    ports:
      - "80:80"
    volumes:
      - type: volume
        source: app-server
        target: /var/log/nginx/
        volume:
          nocopy: true
    networks:
      - app-network

    environment:
      - NGINX_PORT=80


# Volumes
volumes:
  app-server:
    #name: app-server
    #driver: local
    external: true

# Docker Networks
networks:
  app-network:
    name: app-network
    driver: bridge
    external: true
