# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo:5.0.3
    #restart: always
    container_name: mgdata
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: zayro
    networks:
      - app-network
    ports:
      - 27017:27017
    volumes:
      - app-data-mg:/etc/mongo


# Volumes
volumes:
  app-data-mg:
    #name: app-data
    #driver: local
    external: true

# Docker Networks
networks:
  app-network:
    name: app-network
    driver: bridge
    external: true
