CREATE USER 'repluser'@'%' IDENTIFIED BY 'replsecret';
GRANT REPLICATION SLAVE ON *.* TO 'repluser'@'%';
FLUSH PRIVILEGES;
FLUSH TABLES WITH READ LOCK;


RESET MASTER;
SHOW BINARY LOGS;
SHOW MASTER STATUS;

UNLOCK TABLES;
