# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres:13.4
    #restart: always
    container_name: pgdata
    environment:
      POSTGRES_PASSWORD: zayro
    ports:
      - 5432:5432
    volumes:
      - app-data-pg:/var/lib/postgresql/data
    networks:
      - app-network


# Volumes
volumes:
  app-data-pg:
    #name: app-data
    #driver: local
    external: true

# Docker Networks
networks:
  app-network:
    name: app-network
    driver: bridge
    external: true
