version: "3.8"

# Services
services:
  users:
    container_name: user-service
    build: ./user-service
    networks:
      app-network:
        aliases:
          - user_service
  cars:
    container_name: car-service
    build: ./car-service
    networks:
      app-network:
        aliases:
          - car_service

  books:
    build:
      context: ./book-service
      dockerfile: Dockerfile  
    container_name: book-service
    ports:
      - "3000:3000"    
    networks:
      app-network:
        aliases:
          - book_service

# Docker Networks
networks:
  app-network:
    name: app-network
    driver: bridge
    external: true
