FROM php:7-fpm
COPY . /code
WORKDIR /code/blog
RUN docker-php-ext-install pdo pdo_mysql mysqli
#Install Composer
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
RUN php composer-setup.php --install-dir=. --filename=composer
RUN mv composer /usr/local/bin/
#RUN cd /code/blog && php -S localhost:6000 -t public

CMD [ "php", "-S", "0.0.0.0:60", "-t", "public" ]